"""Add github integration fields

Revision ID: 4d01ac430399
Revises: 0001_initial
Create Date: 2026-04-26 18:49:56.448286
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d01ac430399'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt_items', sa.Column('github_issue_url', sa.String(length=512), nullable=True))
    op.add_column('debt_items', sa.Column('fix_pr_url', sa.String(length=512), nullable=True))
    op.add_column('repositories', sa.Column('rag_embedded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'rag_embedded_at')
    op.drop_column('debt_items', 'fix_pr_url')
    op.drop_column('debt_items', 'github_issue_url')
    # ### end Alembic commands ###
