apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: debtlens
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  type: ClusterIP
